name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker server image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          target: server
          tags: ghcr.io/${{ github.repository }}/server:latest
      - name: Build Docker client image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          target: client
          tags: ghcr.io/${{ github.repository }}/client:latest

